import 'package:flutter/cupertino.dart';

class ProfileScreen extends StatelessWidget {
  @override
  Widget build(context) {
    return CustomScrollView(
      slivers: <Widget>[
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
        Text("profile"),
      ],
    );
  }
}
